export const schemaStatements = [
  `create table if not exists settings (
    key text primary key,
    value text not null,
    updated_at text not null
  )`,
  `create table if not exists characters (
    id text primary key,
    name text not null,
    status text not null,
    summary text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists character_constitution_versions (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    version integer not null,
    body text not null,
    change_reason text,
    is_active integer not null default 0,
    approved_at text,
    created_at text not null,
    updated_at text not null,
    unique(character_id, version)
  )`,
  `create table if not exists character_canon_entries (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    title text not null,
    body text not null,
    status text not null,
    source_run_id text references runs(id) on delete set null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists character_memory_entries (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    body text not null,
    source text,
    source_run_id text references runs(id) on delete set null,
    source_type text not null default 'manual',
    confidence real not null default 0.7,
    importance integer not null default 3,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists character_appearance_profiles (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    body text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists character_voice_guides (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    body text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists character_platform_personas (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    platform text not null,
    body text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists reference_images (
    id text primary key,
    character_id text references characters(id) on delete set null,
    file_path text not null,
    original_name text not null,
    mime_type text not null,
    size_bytes integer not null,
    status text not null default 'experimental',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists assets (
    id text primary key,
    character_id text references characters(id) on delete set null,
    run_id text references runs(id) on delete set null,
    prompt_recipe_id text references prompt_recipes(id) on delete set null,
    file_path text,
    kind text not null,
    status text not null,
    provider text,
    original_prompt text,
    negative_prompt text,
    mime_type text,
    size_bytes integer not null default 0,
    metadata_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists asset_analysis (
    id text primary key,
    asset_id text not null references assets(id) on delete cascade,
    provider text not null,
    score real,
    summary text,
    identity_match text,
    identity_score integer not null default 0,
    quality_score integer not null default 0,
    story_fit_score integer not null default 0,
    platform_fit text,
    quality_issues text,
    identity_notes text,
    suggested_prompt_fixes text,
    alt_text text,
    recommended_action text,
    raw_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists runs (
    id text primary key,
    character_id text references characters(id) on delete set null,
    type text not null,
    status text not null,
    title text not null,
    error text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists run_events (
    id text primary key,
    run_id text not null references runs(id) on delete cascade,
    type text not null,
    message text not null,
    payload_json text not null default '{}',
    created_at text not null
  )`,
  `create table if not exists run_artifacts (
    id text primary key,
    run_id text not null references runs(id) on delete cascade,
    kind text not null,
    label text not null,
    artifact_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists run_decisions (
    id text primary key,
    run_id text not null references runs(id) on delete cascade,
    decision text not null,
    rationale text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists provider_jobs (
    id text primary key,
    run_id text references runs(id) on delete set null,
    provider text not null,
    external_id text,
    status text not null,
    request_json text not null default '{}',
    response_json text not null default '{}',
    attempt_index integer not null default 1,
    route_tier text,
    route_reason text,
    fallback_reason text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists comfy_workflows (
    id text primary key,
    name text not null,
    workflow_json text not null default '{}',
    positive_prompt_node text,
    positive_prompt_input text,
    negative_prompt_node text,
    negative_prompt_input text,
    seed_node text,
    seed_input text,
    output_node_ids_json text not null default '[]',
    default_for_tiers_json text not null default '[]',
    status text not null default 'draft',
    validation_error text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists activity_candidates (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    title text not null,
    body text not null,
    location_fiction text,
    activity_type text,
    visual_motif text,
    platform_fit text,
    identity_fit_score real not null default 0,
    campaign_fit_score real not null default 0,
    freshness_score real not null default 0,
    status text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists content_briefs (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    activity_candidate_id text references activity_candidates(id) on delete set null,
    campaign_id text,
    goal text,
    platform_targets text,
    content_pillar text,
    visual_direction text,
    caption_angle text,
    disclosure_flags text,
    desired_outputs text,
    body_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists prompt_recipes (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    content_brief_id text references content_briefs(id) on delete set null,
    constitution_version_id text references character_constitution_versions(id) on delete set null,
    appearance_profile_id text references character_appearance_profiles(id) on delete set null,
    final_prompt text,
    negative_prompt text,
    recipe_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists prompt_runs (
    id text primary key,
    prompt_recipe_id text not null references prompt_recipes(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    provider text not null,
    status text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists drafts (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    content_brief_id text references content_briefs(id) on delete set null,
    prompt_recipe_id text references prompt_recipes(id) on delete set null,
    asset_id text references assets(id) on delete set null,
    created_from_run_id text references runs(id) on delete set null,
    status text not null,
    title text not null,
    body text not null,
    summary text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists platform_variants (
    id text primary key,
    draft_id text not null references drafts(id) on delete cascade,
    platform text not null,
    post_format text,
    caption text not null,
    hashtags text,
    alt_text text,
    disclosure_text text,
    ai_generated_flag integer not null default 1,
    paid_partnership_flag integer not null default 0,
    brand_content_flag integer not null default 0,
    notes text,
    status text not null default 'draft',
    metadata_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists publishing_packages (
    id text primary key,
    draft_id text not null references drafts(id) on delete cascade,
    export_path text not null,
    files_json text not null default '[]',
    status text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists publishing_events (
    id text primary key,
    draft_id text not null references drafts(id) on delete cascade,
    platform text not null,
    status text not null default 'planned',
    live_url text,
    published_at text,
    notes text,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists social_feedback (
    id text primary key,
    draft_id text not null references drafts(id) on delete cascade,
    publishing_event_id text references publishing_events(id) on delete set null,
    character_id text references characters(id) on delete set null,
    platform text not null,
    published_url text,
    impressions integer not null default 0,
    reach integer not null default 0,
    likes integer not null default 0,
    comments integer not null default 0,
    shares integer not null default 0,
    saves integer not null default 0,
    profile_visits integer not null default 0,
    follows_gained integer not null default 0,
    qualitative_notes text,
    top_comments text,
    operator_judgment text,
    feedback_json text not null default '{}',
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists reflections (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    draft_id text references drafts(id) on delete set null,
    social_feedback_id text references social_feedback(id) on delete set null,
    summary text,
    reflection_json text not null default '{}',
    body text not null,
    created_at text not null,
    updated_at text not null
  )`,
  `create table if not exists identity_update_proposals (
    id text primary key,
    character_id text not null references characters(id) on delete cascade,
    run_id text references runs(id) on delete set null,
    kind text not null,
    body text not null,
    rationale text,
    source_run_id text references runs(id) on delete set null,
    source_reflection_id text references reflections(id) on delete set null,
    risk_level text not null default 'low',
    status text not null,
    created_at text not null,
    updated_at text not null
  )`
];

export const additiveColumnStatements = [
  {
    table: "character_constitution_versions",
    column: "change_reason",
    statement: "alter table character_constitution_versions add column change_reason text"
  },
  {
    table: "character_constitution_versions",
    column: "is_active",
    statement: "alter table character_constitution_versions add column is_active integer not null default 0"
  },
  {
    table: "character_canon_entries",
    column: "source_run_id",
    statement: "alter table character_canon_entries add column source_run_id text references runs(id) on delete set null"
  },
  {
    table: "character_memory_entries",
    column: "source_run_id",
    statement: "alter table character_memory_entries add column source_run_id text references runs(id) on delete set null"
  },
  {
    table: "character_memory_entries",
    column: "source_type",
    statement: "alter table character_memory_entries add column source_type text not null default 'manual'"
  },
  {
    table: "character_memory_entries",
    column: "confidence",
    statement: "alter table character_memory_entries add column confidence real not null default 0.7"
  },
  {
    table: "character_memory_entries",
    column: "importance",
    statement: "alter table character_memory_entries add column importance integer not null default 3"
  },
  {
    table: "reference_images",
    column: "status",
    statement: "alter table reference_images add column status text not null default 'experimental'"
  },
  { table: "activity_candidates", column: "location_fiction", statement: "alter table activity_candidates add column location_fiction text" },
  { table: "activity_candidates", column: "activity_type", statement: "alter table activity_candidates add column activity_type text" },
  { table: "activity_candidates", column: "visual_motif", statement: "alter table activity_candidates add column visual_motif text" },
  { table: "activity_candidates", column: "platform_fit", statement: "alter table activity_candidates add column platform_fit text" },
  { table: "activity_candidates", column: "identity_fit_score", statement: "alter table activity_candidates add column identity_fit_score real not null default 0" },
  { table: "activity_candidates", column: "campaign_fit_score", statement: "alter table activity_candidates add column campaign_fit_score real not null default 0" },
  { table: "activity_candidates", column: "freshness_score", statement: "alter table activity_candidates add column freshness_score real not null default 0" },
  { table: "content_briefs", column: "activity_candidate_id", statement: "alter table content_briefs add column activity_candidate_id text references activity_candidates(id) on delete set null" },
  { table: "content_briefs", column: "campaign_id", statement: "alter table content_briefs add column campaign_id text" },
  { table: "content_briefs", column: "goal", statement: "alter table content_briefs add column goal text" },
  { table: "content_briefs", column: "platform_targets", statement: "alter table content_briefs add column platform_targets text" },
  { table: "content_briefs", column: "content_pillar", statement: "alter table content_briefs add column content_pillar text" },
  { table: "content_briefs", column: "visual_direction", statement: "alter table content_briefs add column visual_direction text" },
  { table: "content_briefs", column: "caption_angle", statement: "alter table content_briefs add column caption_angle text" },
  { table: "content_briefs", column: "disclosure_flags", statement: "alter table content_briefs add column disclosure_flags text" },
  { table: "content_briefs", column: "desired_outputs", statement: "alter table content_briefs add column desired_outputs text" },
  { table: "prompt_recipes", column: "content_brief_id", statement: "alter table prompt_recipes add column content_brief_id text references content_briefs(id) on delete set null" },
  { table: "prompt_recipes", column: "constitution_version_id", statement: "alter table prompt_recipes add column constitution_version_id text references character_constitution_versions(id) on delete set null" },
  { table: "prompt_recipes", column: "appearance_profile_id", statement: "alter table prompt_recipes add column appearance_profile_id text references character_appearance_profiles(id) on delete set null" },
  { table: "prompt_recipes", column: "final_prompt", statement: "alter table prompt_recipes add column final_prompt text" },
  { table: "prompt_recipes", column: "negative_prompt", statement: "alter table prompt_recipes add column negative_prompt text" },
  { table: "assets", column: "run_id", statement: "alter table assets add column run_id text references runs(id) on delete set null" },
  { table: "assets", column: "prompt_recipe_id", statement: "alter table assets add column prompt_recipe_id text references prompt_recipes(id) on delete set null" },
  { table: "assets", column: "original_prompt", statement: "alter table assets add column original_prompt text" },
  { table: "assets", column: "negative_prompt", statement: "alter table assets add column negative_prompt text" },
  { table: "assets", column: "mime_type", statement: "alter table assets add column mime_type text" },
  { table: "assets", column: "size_bytes", statement: "alter table assets add column size_bytes integer not null default 0" },
  { table: "asset_analysis", column: "identity_match", statement: "alter table asset_analysis add column identity_match text" },
  { table: "asset_analysis", column: "identity_score", statement: "alter table asset_analysis add column identity_score integer not null default 0" },
  { table: "asset_analysis", column: "quality_score", statement: "alter table asset_analysis add column quality_score integer not null default 0" },
  { table: "asset_analysis", column: "story_fit_score", statement: "alter table asset_analysis add column story_fit_score integer not null default 0" },
  { table: "asset_analysis", column: "platform_fit", statement: "alter table asset_analysis add column platform_fit text" },
  { table: "asset_analysis", column: "quality_issues", statement: "alter table asset_analysis add column quality_issues text" },
  { table: "asset_analysis", column: "identity_notes", statement: "alter table asset_analysis add column identity_notes text" },
  { table: "asset_analysis", column: "suggested_prompt_fixes", statement: "alter table asset_analysis add column suggested_prompt_fixes text" },
  { table: "asset_analysis", column: "alt_text", statement: "alter table asset_analysis add column alt_text text" },
  { table: "asset_analysis", column: "recommended_action", statement: "alter table asset_analysis add column recommended_action text" },
  { table: "drafts", column: "content_brief_id", statement: "alter table drafts add column content_brief_id text references content_briefs(id) on delete set null" },
  { table: "drafts", column: "prompt_recipe_id", statement: "alter table drafts add column prompt_recipe_id text references prompt_recipes(id) on delete set null" },
  { table: "drafts", column: "asset_id", statement: "alter table drafts add column asset_id text references assets(id) on delete set null" },
  { table: "drafts", column: "created_from_run_id", statement: "alter table drafts add column created_from_run_id text references runs(id) on delete set null" },
  { table: "drafts", column: "summary", statement: "alter table drafts add column summary text" },
  { table: "platform_variants", column: "post_format", statement: "alter table platform_variants add column post_format text" },
  { table: "platform_variants", column: "hashtags", statement: "alter table platform_variants add column hashtags text" },
  { table: "platform_variants", column: "alt_text", statement: "alter table platform_variants add column alt_text text" },
  { table: "platform_variants", column: "disclosure_text", statement: "alter table platform_variants add column disclosure_text text" },
  { table: "platform_variants", column: "ai_generated_flag", statement: "alter table platform_variants add column ai_generated_flag integer not null default 1" },
  { table: "platform_variants", column: "paid_partnership_flag", statement: "alter table platform_variants add column paid_partnership_flag integer not null default 0" },
  { table: "platform_variants", column: "brand_content_flag", statement: "alter table platform_variants add column brand_content_flag integer not null default 0" },
  { table: "platform_variants", column: "notes", statement: "alter table platform_variants add column notes text" },
  { table: "platform_variants", column: "status", statement: "alter table platform_variants add column status text not null default 'draft'" },
  { table: "publishing_packages", column: "files_json", statement: "alter table publishing_packages add column files_json text not null default '[]'" },
  { table: "publishing_events", column: "status", statement: "alter table publishing_events add column status text not null default 'planned'" },
  { table: "publishing_events", column: "live_url", statement: "alter table publishing_events add column live_url text" },
  { table: "social_feedback", column: "publishing_event_id", statement: "alter table social_feedback add column publishing_event_id text references publishing_events(id) on delete set null" },
  { table: "social_feedback", column: "character_id", statement: "alter table social_feedback add column character_id text references characters(id) on delete set null" },
  { table: "social_feedback", column: "published_url", statement: "alter table social_feedback add column published_url text" },
  { table: "social_feedback", column: "impressions", statement: "alter table social_feedback add column impressions integer not null default 0" },
  { table: "social_feedback", column: "reach", statement: "alter table social_feedback add column reach integer not null default 0" },
  { table: "social_feedback", column: "likes", statement: "alter table social_feedback add column likes integer not null default 0" },
  { table: "social_feedback", column: "comments", statement: "alter table social_feedback add column comments integer not null default 0" },
  { table: "social_feedback", column: "shares", statement: "alter table social_feedback add column shares integer not null default 0" },
  { table: "social_feedback", column: "saves", statement: "alter table social_feedback add column saves integer not null default 0" },
  { table: "social_feedback", column: "profile_visits", statement: "alter table social_feedback add column profile_visits integer not null default 0" },
  { table: "social_feedback", column: "follows_gained", statement: "alter table social_feedback add column follows_gained integer not null default 0" },
  { table: "social_feedback", column: "qualitative_notes", statement: "alter table social_feedback add column qualitative_notes text" },
  { table: "social_feedback", column: "top_comments", statement: "alter table social_feedback add column top_comments text" },
  { table: "social_feedback", column: "operator_judgment", statement: "alter table social_feedback add column operator_judgment text" },
  { table: "reflections", column: "draft_id", statement: "alter table reflections add column draft_id text references drafts(id) on delete set null" },
  { table: "reflections", column: "social_feedback_id", statement: "alter table reflections add column social_feedback_id text references social_feedback(id) on delete set null" },
  { table: "reflections", column: "summary", statement: "alter table reflections add column summary text" },
  { table: "reflections", column: "reflection_json", statement: "alter table reflections add column reflection_json text not null default '{}'" },
  { table: "identity_update_proposals", column: "rationale", statement: "alter table identity_update_proposals add column rationale text" },
  { table: "identity_update_proposals", column: "source_run_id", statement: "alter table identity_update_proposals add column source_run_id text references runs(id) on delete set null" },
  { table: "identity_update_proposals", column: "source_reflection_id", statement: "alter table identity_update_proposals add column source_reflection_id text references reflections(id) on delete set null" },
  { table: "identity_update_proposals", column: "risk_level", statement: "alter table identity_update_proposals add column risk_level text not null default 'low'" },
  { table: "provider_jobs", column: "attempt_index", statement: "alter table provider_jobs add column attempt_index integer not null default 1" },
  { table: "provider_jobs", column: "route_tier", statement: "alter table provider_jobs add column route_tier text" },
  { table: "provider_jobs", column: "route_reason", statement: "alter table provider_jobs add column route_reason text" },
  { table: "provider_jobs", column: "fallback_reason", statement: "alter table provider_jobs add column fallback_reason text" }
];
